# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: maven:3.3.3
image: rburgst/java8-openjfx-docker

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mvn --version
          - mvn clean install